### ISSUE TITLE
Text is deleted when I want to create another text

### ISSUE THREAD

**Issue by wake-0** [nytopop/askii#1]
Here I tried to create a text:
![image](https://user-images.githubusercontent.com/11227428/77782338-63f9c380-7057-11ea-8bac-719684c1521a.png)

but when I click somewhere else the text is removed:
![image](https://user-images.githubusercontent.com/11227428/77782370-77a52a00-7057-11ea-8618-15335d51cd39.png)

Do I have to click a special key to finish the text input?

**Comment by nytopop** [comment]
> Do I have to click a special key to finish the text input?

Yep, typing `Esc` will save the input, while clicking anywhere on the canvas discards it.

To be honest I didn't think too hard about the ergonomics of this, do you think it should be reversed?

**Comment by wake-0** [comment]
Yeah, I would reverse it. I think it is much more intuitive to press ESC to stop/interrupt the action.

This is not limited to text creation, e.g when I am in box creation mode and I am holding the left mouse button by pressing ESC the whole creation should stop.
(I have not tried it yet, maybe it works out of the box).

**Comment by nytopop** [comment]
That does sound better. Although, it raises an issue with keyboard focus.

Currently, `Esc` will both save the content, and move keyboard focus back to the canvas so you can use keybinds immediately (as they aren't available while a text cursor is active).

So, to avoid holding keyboard focus hostage in a cursor, there would need to be one click to save the content, and another to start a new cursor. Which I'm not really opposed to.

**Comment by wake-0** [comment]
@nytopop I tried the actual solution with the ESC and clicking, it was a very good and smooth feeling.

Thanks, good work!
